# Generated by Django 5.1.5 on 2025-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hracipepa',
            name='tym',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
