# Generated by Django 5.1.5 on 2025-03-27 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepaapp', '0002_hracipepa_tym'),
    ]

    operations = [
        migrations.AddField(
            model_name='hracipepa',
            name='celkem_kroku',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
