# Generated by Django 5.1.5 on 2025-03-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepaapp', '0005_pepa_zakladni_staty_alter_pepaspanek_aktivita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepa_zakladni_staty',
            name='delkakroku',
            field=models.FloatField(default=0),
        ),
    ]
