# Generated by Django 5.1.5 on 2025-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_img', models.ImageField(upload_to='food_images/')),
                ('food_name', models.CharField()),
                ('food_znacka', models.CharField()),
                ('food_typ', models.CharField()),
                ('food_vaha', models.FloatField(default=0)),
                ('food_nazev', models.CharField()),
                ('food_objem', models.FloatField(default=0)),
                ('food_kcal', models.FloatField(default=0)),
                ('food_sytost', models.FloatField(default=0)),
                ('food_hydratace', models.FloatField(default=0)),
                ('food_bonus_typ', models.CharField()),
                ('food_bonus_hodnota', models.FloatField(default=0)),
                ('food_cena', models.FloatField(default=0)),
                ('food_pozn', models.CharField()),
            ],
        ),
    ]
