# Generated by Django 5.1.5 on 2025-03-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_food_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_drink',
            name='food_nazev',
        ),
    ]
